export const ADD_CURRENT_USER = 'ADD_CURRENT_USER'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const ADD_PROJECTS = 'ADD_PROJECTS'
export const REMOVE_PROJECTS = 'REMOVE_PROJECTS'
export const ADD_PROJECTS_FILTERED_BY_ID = 'ADD_PROJECTS_FILTERED_BY_ID'
export const REMOVE_PROJECTS_FILTERED_BY_ID = 'REMOVE_PROJECTS_FILTERED_BY_ID'

export const ADD_TECHS = 'ADD_TECHS'
export const REMOVE_TECHS = 'REMOVE_TECHS'

export const ADD_GITHUB_REPOSITORIES = 'ADD_GITHUB_REPOSITORIES'
