export const ADD_CURRENT_USER = 'ADD_CURRENT_USER'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const ADD_PROJECTS = 'ADD_PROJECTS'
export const REMOVE_PROJECTS = 'REMOVE_PROJECTS'
