export const ADD_CURRENT_USER = 'ADD_CURRENT_USER'

export const ADD_PROJECTS = 'ADD_PROJECTS'
export const ADD_PROJECTS_FILTERED_BY_ID = 'ADD_PROJECTS_FILTERED_BY_ID'

export const ADD_TECHS = 'ADD_TECHS'

export const ADD_GITHUB_REPOSITORIES = 'ADD_GITHUB_REPOSITORIES'
