export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE'
export const SET_LOCALE_START = 'SET_LOCALE_START'
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS'
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR'

export const USER_LOGIN = 'USER_LOGIN'

export const LOAD_STORIES = 'LOAD_STORIES'
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS'
export const LOAD_STORIES_ERROR = 'LOAD_STORIES_ERROR'
export const ADD_STORY = 'ADD_STORY'

export const ADD_UP_VOTE = 'ADD_UP_VOTE'
export const REMOVE_UP_VOTE = 'REMOVE_UP_VOTE'
